//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentsManager2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Net;
    using System.Web.Mvc;

    public partial class Reservation
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "User Is Required")]
        [Display(Name = "User")]
        public int UserId_User { get; set; }
        [Required(ErrorMessage = "Apartment Is Required")]
        [Display(Name = "Apartment")]
        public int ApartmentId_Aparment { get; set; }
        [Required(ErrorMessage ="Start Date Is Required")]
        [Display(Name = "Start Date")]
        public System.DateTime Start_Date { get; set; }
        [Required(ErrorMessage ="End Date is Required")]
        [Display(Name = "End Date")]
        public System.DateTime End_Date { get; set; }
        public virtual User User { get; set; }
        public virtual Apartment Apartment { get; set; }

        public IEnumerable<SelectListItem> UsersToSelect { get; set; }
        public IEnumerable<SelectListItem> ApartmentsToSelect { get; set; }

        public string StartDateFormated => Start_Date.ToString("dd/MM/yy");
        public string EndDateFormated => End_Date.ToString("dd/MM/yy");
        public string ReservationInfo => $"{StartDateFormated} to {EndDateFormated}";

    }
}
